site_name: Xdrip-Android-APS-Nightscout-readthetips
site_url: https://example.com
theme:
    name: material
    language: en
    features:
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.tracking
        - navigation.top
        - search.suggest
        - search.highlight
        - content.code.annotate
    logo: assets/images/T1_xDrip+logo_white_236x236.png
    favicon: assets/images/favicon.png
    palette:
      primary: Black
      scheme: default
    nav_style: primary

extra_css:
    - css/admonitions.css


extra:
  generator: false
markdown_extensions:
    - admonition
    - toc:
        permalink: ⌁

nav:
     - Home: 'index.md'
     - Dexcom :
        - 'Dexcom': 'Dexcom/Userguide.md'
     - Xdrip :
        - 'Download': 'xdrip/xdrip - Download.md'
        - 'Install': 'xdrip/xdrip - install.md'
        - 'xdrip± Settings': 'xdrip/settings.md'
        
        - 'xdrip± Hamburger Menu': 'xdrip/xdrip-HamburgerMenu.md'
        - 'xdrip± Copy Settings': 'xdrip/Copy-settings.md'
        - 'Base URL': 'xdrip/xdrip - Base.md'
        - 'Compatible - Watches': 'xdrip/Compatible Watches.md'
        - 'Xdrip± Follower': 'xdrip/Xdrip Follower Setup.md'
        - 'Hardware Data Source': 'xdrip/xdrip - hardwaredatasource.md'
        - 'G6 & One': 'xdrip/xdrip - Dexcom G6 and Dexcom One.md'
        - 'System Status': 'xdrip/xdrip - System Status.md'
        - 'Start Sensor': 'xdrip/xdrip - Start Sensor.md'
        - 'Connection issues – How to Fix': 'xdrip/Xdrip connection Problem fix.md'
        - 'Setting up Glucose Meters': 'xdrip/Xdrip - Setting up Glucose Meters.md'
     - Nightscout :
        - 'Part 1 - Setting up Github': 'Nightscout/Setting_up_Github_Account_part1.md'
        - 'Part 2 Setting up Heroku Account ': 'Nightscout/Setting_up_Heroku_Account_part2.md'
        - 'Part 3 Setting up Atlas Account ': 'Nightscout/Setting_up_Atlas_Account_part3.md'
        - 'Part 4 - Fork and Deploy cgm remote monitory': 'Nightscout/Part 4 - Fork and Deploy cgm remote monitory.md'
        - 'Nightscout Structure': 'Nightscout/Nightscout Structure.md'
        - 'Compatible - Watches': 'Nightscout/Compatible Watches.md'
        - 'Oracle Cloud Setup': 'Nightscout/Nightscout_Oracle Cloud - setup.md'
        - 'Google Cloud Server Setup': 'Nightscout/Google Cloud_setup.md'
        - 'Fly_io': 'Nightscout/Fly_io-setup.md'
     - Watches :
        - 'CGM onto - Watches': 'watches/Watches.md'
        - 'Compatible - Watches': 'watches/Compatible Watches.md'
        - 'TicWatch-Pro-3-Side-Load - Watches': 'watches/TicWatch-Pro-3-side-load---xdrip.md'
     
        
      
     - Helpful Links: 'Helpful/Helplinks.md'
     - about: about.md




